import Head from 'next/head';

import siteInfo from '@data/siteInfo';

import Header from './Header';
import Footer from './Footer';

const Layout = (props) => {
  // console.log(siteInfo);
  const { pageTitle } = props;
  return (
    <>
      <Head>
        <title>{(pageTitle && `${siteInfo.title} | ${pageTitle}`) || siteInfo.title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header>
        <h1 className="pageTitle">{pageTitle}</h1>
      </Header>
      {/* <pre>{JSON.stringify(siteInfo, null, 2)}</pre> */}
      <main>{props.children}</main>
      <Footer></Footer>
    </>
  );
};

export default Layout;
